### ISSUE TITLE
Review MultipleArbitrableTransaction

### ISSUE THREAD

**Issue by clesaege** [kleros/kleros-interaction#140]
- Look at this https://github.com/kleros/kleros-interaction/blob/master/contracts/standard/arbitration/MultipleArbitrableTransaction.sol contract for bugs and vulnerabilities.
- Write a review on it which can be as short (no issues) or as long (complex vulnerabilities) as it is necessary.
- This task is made to be duplicated.

**Comment by ferittuncer** [comment]
- Enums could be used instead of magic numbers.
- Require check in line 319 (`require(_disputeID == transaction.disputeId, "Wrong dispute ID.");`) may be unnecessary, I can't think of a situation it fails unless there is a hardware level error in calculations.
- In line 303, I would say `_amountToBeReimbursed` instead of `_amountReimbursed` which made me think it is a counter which tracks reimbursed amount so far.
- *BySeller *ByBuyer functions could be merged into one if the resulting function is not getting too messy. If it gets too messy, this is good.

**Comment by epiqueras** [comment]
https://docs.google.com/document/d/12b9gm6RnXMri7uanysjFDR7XuO5EeF8i-QZkdAw4VuE/edit?usp=sharing

**Comment by n1c01a5** [comment]
`pay` and `reimburse` functions could also be merged into one

**Comment by n1c01a5** [comment]
something seems buggy with the timeout, for example for this transaction the buyer 0x580b9ca15035b8c99bda7b959eab185b40b19704 raise a timeout but the eth are sent to the seller see https://kovan.etherscan.io/tx/0x85ee70e14a16d1e392a2cb2d2ff62f0658156356e9b2e3d488d0e574076c27cf

**Comment by epiqueras** [comment]
Yeah, time outs are broken, see the first "Major" point in my review.

**Comment by n1c01a5** [comment]
1st major issue (timeout) fixed with https://github.com/kleros/kleros-interaction/pull/149

**Comment by satello** [comment]
https://docs.google.com/document/d/1OUzo2rHlLbNYDiqQi2b-E4Ad0UvINlkNtC_V8DIGZec/edit

**Comment by yushih** [comment]
https://docs.google.com/document/d/1CdGj5KEw3c4XyaRjzpeDZZ81WWlKJjfT06zmXqRFpJM/edit?usp=sharing

**Comment by n1c01a5** [comment]
@epiqueras https://github.com/kleros/kleros-interaction/pull/165

**Comment by mtsalenc** [comment]
https://docs.google.com/document/d/1FWR93O40Teb3o4XbC3MD3bajQRPQ3WY4ENmt4u6WPb8/edit?usp=sharing

**Comment by epiqueras** [comment]
@n1c01a5 Please make new issue following https://kleros.gitbook.io/contributing-md/smart-contract-workflow/reviews-and-bug-bounties#pre-review, to prepare for bounties
