### ISSUE TITLE
Pre-Review ArbitrableTokenList

### ISSUE THREAD

**Issue by mtsalenc** [kleros/kleros-interaction#158]
https://github.com/kleros/kleros-interaction/blob/master/contracts/standard/permission/ArbitrableTokenList.sol

**Comment by mtsalenc** [comment]
I'm adding @epiqueras's suggestions for history purposes:

```
- *You're still setting disputed to false, when it should be a historic record of wether an agreement was ever disputed. You are also requiring that the last agreement was not disputed to create a new one. This might break internal logic.*
- Some param ordering is off.
- You can move the `lastAction == 0 push tokenID` to the `latestAgreementID != 0x0` block.
- Do we really need to clear `challengeReward`?
- latestAgreementID() is unnecessary.
- *You need to factorize ruling in favor of either party, it's repeated way too many times.*
- *In `itemsCount()`, `disputed` should not be exclusive.*
- *The fundDisputeCache should always be cleared, currently it's only cleared if it's the agreement's first contribution.*
- Valid rulings are already enforced higher up in the inheritance `<= choices`, I think, let's not repeat it.
```

**Comment by epiqueras** [comment]
@mtsalenc Can you make a new issue, following: https://kleros.gitbook.io/contributing-md/smart-contract-workflow/reviews-and-bug-bounties#pre-review

**Comment by unknownunknown1** [comment]
https://docs.google.com/document/d/1BdT3H5sQ72ZtI6w2E8lG1NnTmreUHn09eqBl6VTm80I/edit?usp=sharing

**Comment by clesaege** [comment]
My review  https://docs.google.com/document/d/1oPVP7_elgQQWAhQDJEAi1Mt9qE8fxdOpXwfsI_Ems7Q/edit?usp=sharing

**Comment by ferittuncer** [comment]
### Review for 47245c018


- Typo in comment "Arbitrator did not rule **of** refused to rule."
https://github.com/kleros/kleros-interaction/blob/47245c0181f9ad7f1dab19d751e1584e39ec501b/contracts/standard/permission/ArbitrableTokenList.sol#L65 

- Is it OK to prevent evidence submissions if `round.appealed`? https://github.com/kleros/kleros-interaction/blob/47245c0181f9ad7f1dab19d751e1584e39ec501b/contracts/standard/permission/ArbitrableTokenList.sol#L814-L822

- It can be a problem to uniquely identify a token with `symbolURI` I think, because it can be easily replaced. For example, someone can make multiple submissions for token X and only diference is `symbolURI` but those different uris has the same symbol so effectively they are duplicate submissions interpreted like original submissions. https://github.com/kleros/kleros-interaction/blob/47245c0181f9ad7f1dab19d751e1584e39ec501b/contracts/standard/permission/ArbitrableTokenList.sol#L249-L257

- Is it intended to declare `Party.Challenger` as `winner` when `currentRuling == RulingOption.Other`? https://github.com/kleros/kleros-interaction/blob/47245c0181f9ad7f1dab19d751e1584e39ec501b/contracts/standard/permission/ArbitrableTokenList.sol#L780-L790

- I can't see where token status is updated in `fundPotDispute(...)` but this function emits `TokenStatusChange`. Is it intended? https://github.com/kleros/kleros-interaction/blob/47245c0181f9ad7f1dab19d751e1584e39ec501b/contracts/standard/permission/ArbitrableTokenList.sol#L382-L453

**Comment by mtsalenc** [comment]
Great finds!

> It can be a problem to uniquely identify a token without symbolURI, I think, since we can't tell whether a symbol is the correct one or not and updates would have to be handled via disputes. So disputes would need to handle also updating the image instead of just inclusion + removal from the list.

**Comment by mtsalenc** [comment]
Great finds!

**Comment by clesaege** [comment]
New review: https://docs.google.com/document/d/15cPuLcLuQ3vtnBxv0Ah6Qw3g9uyJzNtkhO86nOBTY3Q/edit#

**Comment by unknownunknown1** [comment]
Another review https://docs.google.com/document/d/1uxtYa47fv0UsVGa7rwU_xAXR1rm1ngr6TR5bVq_8_rk/edit?usp=sharing
Mostly typos

**Comment by unknownunknown1** [comment]
https://docs.google.com/document/d/17XROpKQNHaN_G8_poEdJZxz51FPBi_PdPf0vePXYJnc/edit?usp=sharing

**Comment by epiqueras** [comment]
https://docs.google.com/document/d/1Un-eDVkBrNbwagTOZytd_FDtd2mcx59pwB3hQsXreKM/edit

**Comment by ferittuncer** [comment]
https://docs.google.com/document/d/1BPkSWKWxFX2EmFFjzdAZaQACc7rAUZR8QRQkn4mnAwc/edit?usp=sharing

**Comment by clesaege** [comment]
Latest review https://docs.google.com/document/d/1u-Hj8iIUqp0MqtgOVcLzWJcMZjmwj8F6L87D6ZOSpaU/edit#

**Comment by mtsalenc** [comment]
Bug: Here, we the ID of the MetaEvidence should be:
```
     ? 2 * metaEvidenceUpdates
      : 2 * metaEvidenceUpdates + 1,
```
https://github.com/kleros/kleros-interaction/blob/dfe4ac98af97ef01c41ab302aa504e5db98aaa95/contracts/standard/permission/ArbitrableTokenList.sol#L388

**Comment by clesaege** [comment]
Nico review: https://docs.google.com/document/d/1IcHqmtG8fB0Ss91Oi1B8zgAike9xUM75q_gXmeEFrT4/edit#

**Comment by unknownunknown1** [comment]
https://docs.google.com/document/d/1kX4SMTjVhYnHevDfWclckSiZQ-MI3NWnpMdlv-tLCC4/edit?usp=sharing

**Comment by clesaege** [comment]
Good catch @unknownunknown1 . I fix it.

**Comment by unknownunknown1** [comment]
Review of the new version https://docs.google.com/document/d/1bUyLKVExjR10kp97v1ncqDfVuYDY9tzVqzIL6jf0lQg/edit?usp=sharing

**Comment by satello** [comment]
https://docs.google.com/document/d/1OyoypY2VYGg4rT15vXFYNAdeRLH30ruZ9tGVPcfwZSg/edit?usp=sharing
