### ISSUE TITLE
Set / get. Price / cost. Consistency makes is easier to read.

### ISSUE THREAD

**Issue by marsrobertson** [kleros/kleros-interaction#253]
https://github.com/kleros/kleros-interaction/blob/96b34176090e3a17d5208f3093ec15a4482d7c43/contracts/standard/arbitration/CentralizedArbitrator.sol#L44-L46

https://github.com/kleros/kleros-interaction/blob/96b34176090e3a17d5208f3093ec15a4482d7c43/contracts/standard/arbitration/CentralizedArbitrator.sol#L52-L54

Believe me or not, for a few moments I was analyzing what is the difference between **PRICE** and **COST**

### Suggestion:

```
function setArbitrationPrice(uint _arbitrationPrice) public onlyOwner { arbitrationPrice = _arbitrationPrice; }
function getArbitrationPrice(bytes _extraData /* unused */) public view returns(uint fee) { return arbitrationPrice; }
```

Developers across frameworks and languages are familiar with get / set and here it is simple enough.

**Comment by ferittuncer** [comment]
Well, you are right. But `arbitrationCost` function is in the standard already. We could use the same name for the variable and then we could have `setArbitrationCost` function. But the problem is a variable with the same name shadows function declaration. This problem may be solved in Solidity compiler in future, then we can reconsider.
