### ISSUE TITLE
the buyer hasn't any incentive to pay the seller

### ISSUE THREAD

**Issue by n1c01a5** [kleros/kleros-interaction#27]
for the arbitrable payment https://github.com/kleros/kleros-interaction/blob/master/contracts/standard/arbitration/ArbitrableTransaction.sol the buyer hasen't any incentive to pay the seller (except maybe to keep good relationship with him) in contrary because it costs `gas`. So the seller must do always raise a dispute and do a `timeout` request, 2 txs.
I propose to solve it the buyer makes a deposit and if he doesn't pay the seller in this case, he looses it.
An another one would be to make payment automatic if no challenge within a defined period of time with action callback (alarm clock).

**Comment by clesaege** [comment]
We can make a smart contract implementing that with a 1 contract- multiple transactions in order not to redeploy every times.

**Comment by n1c01a5** [comment]
@epiqueras propose to add a `timeoutTrade` with a `withdraw` function and a deposit to pay the `gas` to solve this issue

**Comment by epiqueras** [comment]
I think we can get rid of `pay()` since the buyer will never have an incentive to pay before the timeout unless we penalize him. But, why penalize and make the code more complex if we can just have the seller withdraw, and have him take the gas he will spend on withdrawing into account when setting the price of the transaction.

This means we only need to remove `pay()`, add `withdraw() onlySeller ifPastTimeout ifNoDispute`, and change the contract so it supports multiple transactions (no redeploy), and make the seller initialize transactions instead of the buyer, because he is the one who should decide the timeout.

```solidity
struct Transaction {
  seller;
  buyer;
  amount;
  timeout;
  disputed;
}
```

What do you think? @clesaege

**Comment by clesaege** [comment]
@epiqueras @n1c01a5 Being nice is sometimes an incentive, also for repeated business.
I don't think the buyer should deposit gas, that increases complexity.

For the other comments yeah, it's not really a change, it's a whole new contract :)

**Comment by epiqueras** [comment]
@clesaege So you are ok with the seller being able to withdraw the money after the timeout?

**Comment by clesaege** [comment]
If not disputed yeah.

**Comment by eburgos** [comment]
Hi, regarding this issue. Please review #32 . I'm curious about if I solved it or I messed it up 🤣 

Regards,

**Comment by clesaege** [comment]
Yeah, here there is a timeout so if the payer does not do anything, the transaction is processed.

**Comment by clesaege** [comment]
In the multiple it works due to timeouts.

**Comment by epiqueras** [comment]
Yeah I put it in the spec.
