### ISSUE TITLE
Remove Dispute event and rename LinkMetaEvidence into it

### ISSUE THREAD

**Issue by clesaege** [kleros/kleros-interaction#75]
The current Dispute event has been deprecated. LinkMetaEvidence is the the updated version and no need to keep both.

**Comment by dannybabbev** [comment]
https://github.com/kleros/kleros-interaction/blob/master/contracts/standard/arbitration/ArbitrableDeposit.sol#L145

Should this line be replaced with `emit LinkMetaEvidence(arbitrator,disputeID,0)` or removed?

**Comment by clesaege** [comment]
We need:
-Add an argument in the constructor to emit the MetaEvidence event.
-Emit the Dispute event linking it when a dispute is created.
-Update tests accordingly.

**Comment by dannybabbev** [comment]
Currently `emit Dispute` is used in three places:

- https://github.com/kleros/kleros-interaction/blob/master/contracts/standard/arbitration/MultipleArbitrableTransaction.sol#L161

- https://github.com/kleros/kleros-interaction/blob/master/contracts/standard/arbitration/TwoPartyArbitrable.sol#L104

- https://github.com/kleros/kleros-interaction/blob/master/contracts/standard/arbitration/ArbitrableDeposit.sol#L145

You want to refactor `emit Dispute` to `emit LinkMetaEvidence`. That is to just delete `emit Dispute`, since `emit LinkMetaEvidence` is already there in 2/3 of the places where Dispute is emitted.

The only place where `Dispute` is emitted and `LinkMetaEvidence` is not emitted is here:
https://github.com/kleros/kleros-interaction/blob/master/contracts/standard/arbitration/ArbitrableDeposit.sol#L145

I do not understand what you mean by:

-   _"Add an argument in the constructor to emit the MetaEvidence event"_: Dispute is not emitted in the `constructor` but on `raiseDispute()` only. Second, do you mean `LinkMetaEvidence` event or `MetaEvidence` event?
-  _"Emit the Dispute event linking it when a dispute is created"_: You said that the `Dispute` event is deprecated, why would you want to emit it now? Do you mean emit `LinkMetaEvidenceEvent`?

As I said, `LinkMetaEvidence` is not emitted where a `Dispute` is emitted only [here](https://github.com/kleros/kleros-interaction/blob/master/contracts/standard/arbitration/ArbitrableDeposit.sol#L145). However, here there is no `_metaEvidenceID`, so maybe the meta evidence should be emitted like `emit LinkMetaEvidence(arbitrator,disputeID,0)` - that's what's done [here](https://github.com/kleros/kleros-interaction/blob/master/contracts/standard/arbitration/TwoPartyArbitrable.sol#L105)

**Comment by clesaege** [comment]
> You want to refactor emit Dispute to emit LinkMetaEvidence. That is to just delete emit Dispute, since emit LinkMetaEvidence is already there in 2/3 of the places where Dispute is emitted.

-If LinkMetaEvidence is there, it need to be replace with the new version of dispute. The old version of dispute should be removed.

> "Add an argument in the constructor to emit the MetaEvidence event": Dispute is not emitted in the constructor but on raiseDispute() only.

Yeah, as your quote says, I speak about `MetaEvidence`.

> Second, do you mean LinkMetaEvidence event or MetaEvidence event?

As the quote says "MetaEvidence ".

> "Emit the Dispute event linking it when a dispute is created": You said that the Dispute event is deprecated, why would you want to emit it now? Do you mean emit LinkMetaEvidenceEvent?

Old dispute event is deprecated into nothing. `LinkMetaEvidenceEvent` is renamed `Dispute`.

> As I said, LinkMetaEvidence is not emitted where a Dispute is emitted only here.

It should be replaced by the new `Dispute` event. We need to have the `MetaEvidence` in the constructor.

You can look at the historic of modifications in https://github.com/kleros/kleros-interaction/blob/master/contracts/standard/permission/ArbitrablePermissionList.sol and do the same for other files.
Note that when the constructor is changed, test should also be.
